--- 
hosts: 
  - 
    autostart: true
    box: centos/7
    branch: 
    gateway: "192.168.2.1"
    identifier: sb-01.int.dc-01.m4kr.net
    ip: "192.168.2.162"
    mac: 52540fc9cf91
    folders:
      - 
        map: ./conf
        to: /vagrant
    name: sb-01.int.dc-01.m4kr.net
    netmask: "255.255.255.0"
    timezone: "America/Chicago"
    provider: 
      - 
        directive: memory
        value: "4096"
      - 
        directive: cpus
        value: "4"
path: "."
